### ISSUE TITLE
生成されるapp.ymlのBEAR_Session.pathは、 'scheme://host1:port,scheme://host2:port' かと思います。

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bearsaturday/manual#39]
```
init-appで生成されるapp.ymlですが
BEAR_Session.pathは
path: array('host1','host2') でなく、
path: 'scheme://host1:port,scheme://host2:port' かと思います。


# セッション:                                                              

#  adaptor int   アダプター 0 なし | 1 File | 2 DB | 3 memchache
#  prefix string セッションキーにつけるプリフィックス
#  path   string '/tmp/' | 'mysqli://user:password@localhost/' | 
array('host1','host2')
#  idle   int    アイドル時間
#  expire int    セッション切れ時間(秒)
BEAR_Session:
  adaptor: 1
  prefix: ''
  idle  : 400
  expire: 3000
```

Original issue reported on code.google.com by `yuki.ma...@excite.jp` on 16 Aug 2011 at 1:10
